### PR TITLE
fix(ProofOfHumanity): contract update

### PR DESCRIPTION
**Pull request by unknownunknown1**
Quick overview of the changes:

1. Bumped the contract's version to 0.6. Updated `kleros/erc-792` dependency. Also bumped the version of the contracts in "test-purposes" folder, but haven't updated the test file yet.
2. `Submission `and `Request` structs are reorganized and their values are now hashed and not stored.
3. Most of the storage variables now use smaller `uint `types for more efficiency. Library` SafeCast.sol` is added to perform the `uint `conversion. `CappedMath.sol` is replaced with the updated local version, which supports `uint64 `type.
4. Added the events that match the signature of functions of the previous contract version. Some functions had to be renamed to avoid name collision.
5. `submissionChallengeBaseDeposit `is removed and the function `withdrawFeesAndRewards `is simplified in the process.
6. Some refactor changes based on the latest review https://docs.google.com/document/d/14LVWbnw8r2GM10L0ZlA658pmXqNN3L2xDKMZtM2hGXQ/edit
7. Removed the require for resolved request from `submitEvidence`
8. `addSubmission ` function is split into 2 to avoid complexity. `executeRuling` is now `public` and should be invoked manually because arbitrator doesn't have all the necessary data to invoke it.

Other notes:

1. The spreadsheet that compares the gas costs of the old and the new version https://docs.google.com/spreadsheets/d/1BZJPJ9EZAz6WKJ2P4wokXVdn_OUqY1DZ04PdleHU-hI/edit#gid=0 
The most notable gain is in addSubmission function which is 1.5 times cheaper in the new version. The rest of the functions - not so much, if at all.
2. Because most of the values are not stored now, some of the functions, particularly the ones that use vouches, now require complex inputs.

### CODE REVIEW

**Comment by epiqueras** [comment]
Am I reading the sheet wrong, or did most of the functions become more expensive?

**Comment by fnanni-0** [comment]
I'll do a full review soon, but for now here are my two cents:

1. Variable packing in structs only happen in storage, not in calldata and memory. Using smaller uints makes sense in Round and Challenge structs but not in Request and Submission.
2. Using memory instead of calldata for function arguments is more expensive. In some functions (addVouch, removeVouch, fundAppeal, fundSubmission, withdrawFeesAndRewards, submitEvidence) calldata could be used. When using a struct instance with 10 elements, for example, using calldata saves ~3k gas (source: some dirty tests in Remix). 
3. [submissionDisputeIDs, submissionRulings, submissionRounds ](https://github.com/Proof-Of-Humanity/Proof-Of-Humanity/pull/18/files#diff-0b08939fc06b0c962b3fb9c62fb3f50dR128-R130) could be merged into a single mapping pointing to a struct that contains disputeID, ruling and Rounds.

**Comment by fnanni-0** [comment]
> I'll do a full review soon, but for now here are my two cents:
> 
> 1. Variable packing in structs only happen in storage, not in calldata and memory. Using smaller uints makes sense in Round and Challenge structs but not in Request and Submission.
> 2. Using memory instead of calldata for function arguments is more expensive. In some functions (addVouch, removeVouch, fundAppeal, fundSubmission, withdrawFeesAndRewards, submitEvidence) calldata could be used. When using a struct instance with 10 elements, for example, using calldata saves ~3k gas (source: some dirty tests in Remix).
> 3. [submissionDisputeIDs, submissionRulings, submissionRounds ](https://github.com/Proof-Of-Humanity/Proof-Of-Humanity/pull/18/files#diff-0b08939fc06b0c962b3fb9c62fb3f50dR128-R130) could be merged into a single mapping pointing to a struct that contains disputeID, ruling and Rounds.

For 2. notice that if you decide to use calldata you would also need to have a version of hashRequest() and hashSubmission() that uses calldata arguments. Otherwise said savings would be lost.

**Comment by fnanni-0** [comment]
I wonder how to old version performs if the more efficient Request and Submission structs are used...

**Comment by epiqueras** [comment]
Looking at the spreadsheet, 3K won't make it clearly better than the old version.

**Comment by fnanni-0** [comment]
Yaeh agree. For some of these functions both request and submission are arguments, so it's ~6k, which also isn't a huge change

**Comment by unknownunknown1** [comment]
> Am I reading the sheet wrong, or did most of the functions become more expensive?

Oddly enough, yes, they are

**Comment by unknownunknown1** [comment]
> * Variable packing in structs only happen in storage, not in calldata and memory. Using smaller uints makes sense in Round and Challenge structs but not in Request and Submission.
> * Using memory instead of calldata for function arguments is more expensive. In some functions (addVouch, removeVouch, fundAppeal, fundSubmission, withdrawFeesAndRewards, submitEvidence) calldata could be used. When using a struct instance with 10 elements, for example, using calldata saves ~3k gas (source: some dirty tests in Remix).
> * [submissionDisputeIDs, submissionRulings, submissionRounds ](https://github.com/Proof-Of-Humanity/Proof-Of-Humanity/pull/18/files#diff-0b08939fc06b0c962b3fb9c62fb3f50dR128-R130) could be merged into a single mapping pointing to a struct that contains disputeID, ruling and Rounds.

1. Yeah, you're right
2. I was under the impression it's more correct to use

**Comment by unknownunknown1** [comment]
> > I'll do a full review soon, but for now here are my two cents:
> > 
> > 1. Variable packing in structs only happen in storage, not in calldata and memory. Using smaller uints makes sense in Round and Challenge structs but not in Request and Submission.
> > 2. Using memory instead of calldata for function arguments is more expensive. In some functions (addVouch, removeVouch, fundAppeal, fundSubmission, withdrawFeesAndRewards, submitEvidence) calldata could be used. When using a struct instance with 10 elements, for example, using calldata saves ~3k gas (source: some dirty tests in Remix).
> > 3. [submissionDisputeIDs, submissionRulings, submissionRounds ](https://github.com/Proof-Of-Humanity/Proof-Of-Humanity/pull/18/files#diff-0b08939fc06b0c962b3fb9c62fb3f50dR128-R130) could be merged into a single mapping pointing to a struct that contains disputeID, ruling and Rounds.
> 
> For 2. notice that if you decide to use calldata you would also need to have a version of hashRequest() and hashSubmission() that uses calldata arguments. Otherwise said savings would be lost.

Noted, thanks. I was thinking to do 3 myself, but didn't want to clutter it with any more stucts.
I was also under the impression that the functions have to use `calldata `if they're `public ` but maybe I'm wrong in this

**Pull request closed without merging**
